---
- name: Ensure Apache is installed
  apt:
    name: apache2
    state: present

- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- name: Configure Apache ports
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: Restart Apache